### ISSUE TITLE
Post repeats when your reach end of feed on PeerQuery

### ISSUE THREAD

**Issue by tobias-g1** [PeerQuery/Alpha#1]
#### Expected behavior
When you reach the end of a feed on PeerQuery you should be informed that there are no more posts to show. 

#### Actual behavior
When you reach the end of a feed on PeerQuery and you have seen all of the available posts the last post of the feed will repeat when you click the see more button.

#### How to reproduce
1.  Go to https://www.peerquery.com/
2. Click on Gigs in the top nav, you will gig feed and you feed will be selected to show trending. 
3.  Scroll to the bottom until to see you see more trending
4. Keep pressing this button until it reaches the end of the list. 
5. When you reach the end of the list the last post shown will keep repeating. 

Note: I believe that this would be able to be repeated on any of the various different feeds, I simply chose gigs because it seemed to be fairly small so easy to show in the video.

Browser: Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit))
Operating system: MacOS HighSierra Version 10.13

#### Recording Of The Bug
A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/grix2yq1
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/post-repeats-when-your-reach-end-of-feed-on-peerquery">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Dzivenu** [comment]
Nice work @tobias-g1 , issue has been resolved!
